name: Panchayat Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm install

      - name: Run Bot
        env:
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
        run: node path/to/index.js
